// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
import type { Metadata } from 'next';
import { Caladea, Changa_One } from 'next/font/google';
import './globals.css';

const caladea = Caladea({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-caladea',
});

const changaOne = Changa_One({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-changa-one',
});

export const metadata: Metadata = {
  title: "Thobias' Portfolio",
  description: 'Personal Portfolio Archive & Dossier System',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${caladea.variable} ${changaOne.variable}`}>
      <body className="antialiased bg-[#252424] text-white min-h-screen">
        {children}
      </body>
    </html>
  );
}
